# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Timothy Lock
description: "Timothy Lock Portfolio Software Developer"
keywords: "Timothy Lock, Golang, Python, JS, SQL, Kubernetes, software"
url: https://timothylock.ca
baseurl: ""

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Timothy Lock
  job: Software Developer
  bio: "Software developer currently working at Wattpad. Golang, Python, JS, SQL, Kubernetes. Powered by coffee"
  thumb: /images/author.jpg
  email: me@timothylock.ca
  url: https://timothylock.ca/
  github: https://github.com/timothylock
  twitter: https://twitter.com/timothyklock
  instagram: https://www.instagram.com/itstimofee/
  linkedin: https://linkedin.com/in/timothylock
  status: https://status.timothylock.ca

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
